# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      #- name: Run Tests
      #  uses: actions/setup-node@v1
      #  run: node test.js
      # ... etc

name: Tests

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - timeout: 4
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Install gdb gdbserver and openmpi ubuntu
        run: |
          sudo apt-get install gdb gdbserver openmpi-bin libopenmpi-dev
      - name: Compiling node_names
        run: |
          cd gdbgui-mpi && ./compile.sh
      - name: Execute Tests
        run: |
          nox --non-interactive --session tests-${{ matrix.python-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Lint
        run: |
          nox --non-interactive --session lint

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Verify Docs
        run: |
          nox --non-interactive --session docs
